### ISSUE TITLE
Title: Personal webpage with typewriter effect 

### ISSUE THREAD

**Issue by thegoodgamer14** [varunKT001/awesome-javascript-projects#103]
### Describe your issue.

This will be a personal webpage with my basic credentials and links to my social media handles like `Instagram`, `Twitter`, `Linkedin`, `GitHub` etc.
This page will have a typewriter effect and will use the words `Student`, `Developer`, and `Writer` in 3-second intervals.

**Comment by varunKT001** [comment]
@thegoodgamer14 Go ahead 🚀
