### ISSUE TITLE
Feature Request: Back to top button

### ISSUE THREAD

**Issue by anuragasawa20** [varunKT001/awesome-javascript-projects#105]
### Is your feature request related to a problem? Please describe.

I want to add back to top button on gym website

### Describe the solution you'd like.

I will add a button and using javascript i will add feature when screen is scrolled we can go to top using that button

### Additional context (if any)

please assign to me under hacktober tag

**Comment by varunKT001** [comment]
@anuragasawa20 Go ahead 🚀
