### ISSUE TITLE
Title: A QR Code Generator

### ISSUE THREAD

**Issue by SanDiego2049** [varunKT001/awesome-javascript-projects#109]
### Describe your issue.

I can contribute a qr code generator that takes in a url and generates it's unique qr code with a varying list of dimensions to pick from

**Comment by varunKT001** [comment]
@SanDiego2049 

I guess you would need a library for that, and using libraries is not allowed 😕 

If you implement it from scratch, please tell me, and I'll assign this issue.

**Comment by SanDiego2049** [comment]
I didn't use a library per say. I just used qrcode.js to get the qr to actually display and it was just 7 lines out of about 60. I'd understand if it still isn't allowed though, the rules is the rules.

**Comment by varunKT001** [comment]
@SanDiego2049 



Yes, [qrcode.js](https://davidshimjs.github.io/qrcodejs/) is a JavaScript library. Unfortunately, using libraries is not permitted. If you have any more JavaScript project ideas, I'd be delighted to hear them.

Thanks!
