### ISSUE TITLE
Tech Blogs Website Homepage

### ISSUE THREAD

**Issue by geetika001** [varunKT001/awesome-javascript-projects#119]
### Describe your issue.

@varunKT001 can I please add this Technical Blogs website.It is animated as well.Hoping to get the the issue assigned   be considered for Hacktoberfest.
Screenshots of how it looks:
![image](https://user-images.githubusercontent.com/98944568/198098548-6722a8a9-14c6-421a-8a35-94e45fba95e8.png)
![image](https://user-images.githubusercontent.com/98944568/198098626-369c478b-a945-415f-892b-b4215eb1816c.png)
![image](https://user-images.githubusercontent.com/98944568/198098716-9602f68d-4802-4405-8ce5-834baa5119dc.png)

**Comment by varunKT001** [comment]
> I have added the PR.Please review it and do accept it.

I have reviewed your PR. Unfortunately, you can use no JS/CSS libraries in the projects. So, I can't accept the PR, sorry.
