### ISSUE TITLE
Title: Add Link Tree Template 

### ISSUE THREAD

**Issue by ravish036** [varunKT001/awesome-javascript-projects#42]
### Describe your issue.

This is an Link Tree Template which can be used to create an link tree for personal or business purpose just by making changes in existing code. You just have to add the links , Name , Intro & the profile image.

### Screenshots (if applicable).

![image](https://user-images.githubusercontent.com/84343005/194290827-fc2d3f08-4fd2-4093-8d79-01e8ba6edcb0.png)

### Additional context (if any)

Tech stack - HTML5 CSS3 Bootstrap

I want to add this project in your repository under Hacktoberfest'22.

**Comment by varunKT001** [comment]
@ravish036 

The project doesn't seem to use any JavaScript 😕 Maybe you can try to use some JavaScript libraries like `particle.js` to create a nice background for the link tree.

If you are willing to do so, please tell me, and I'll assign you this issue 👍

**Comment by ravish036** [comment]
> @ravish036
> 
> The project doesn't seem to use any JavaScript 😕 Maybe you can try to use some JavaScript libraries like `particle.js` to create a nice background for the link tree.
> 
> If you are willing to do so, please tell me, and I'll assign you this issue 👍

> okay sure, I can add a nice background to it using particle.js
