### ISSUE TITLE
Title:  Fitness Freak (Add Gym website)

### ISSUE THREAD

**Issue by ravish036** [varunKT001/awesome-javascript-projects#49]
### Describe your issue.

It is an website through which a person can register to access you facility. It contains all the description of the fitness plans, trainers etc...

### Screenshots (if applicable).

![image](https://user-images.githubusercontent.com/84343005/194284720-843fbc81-14dc-4486-85f5-b7d1a28b9a57.png)
![image](https://user-images.githubusercontent.com/84343005/194284876-084e78f3-1c03-43cb-bbbb-4f07be7cd385.png)
![image](https://user-images.githubusercontent.com/84343005/194285024-66fe83f9-4717-4cc3-93cd-0b27c63ea02f.png)

### Additional context (if any)

Tech Stack - HTML5 CSS3 JavaScript.

I want to add this project in your repo under Hacktoberfest'22

**Comment by varunKT001** [comment]
@ravish036 Go ahead 🚀

**Comment by ravish036** [comment]
@varunKT001 
please add the lable.

**Comment by ravish036** [comment]
@varunKT001 
I have a doubt, previously I have submitted this gym web on another project in hacktoberfest and now that project is exluded from hacktoberfest'22 so, can I add my gym web here !!

**Comment by varunKT001** [comment]
@ravish036 

Please share the repository link of that project.
