### ISSUE TITLE
Feature Request:Adding more styling and navbar to food ordering website

### ISSUE THREAD

**Issue by anuragasawa20** [varunKT001/awesome-javascript-projects#50]
### Is your feature request related to a problem? Please describe.

i want to add features on food ordering system.  

### Describe the solution you'd like.

add nav bar orders status

**Comment by anuragasawa20** [comment]
Please assign this to me and add hacktober tag to contribution

**Comment by varunKT001** [comment]
@anuragasawa20 Go ahead 🚀

**Comment by Anand271** [comment]
Can you assign this issue to me I know good web designing

**Comment by varunKT001** [comment]
@Anand271 This issue is already assigned to @anuragasawa20
