### ISSUE TITLE
Title: rgb to hex color code converter 

### ISSUE THREAD

**Issue by ravish036** [varunKT001/awesome-javascript-projects#52]
### Describe your issue.

It convert RGB color code to hex color code and vice versa.
Tech stack :- HTML CSS JAVASCRIPT 

### Additional context (if any)

Consider thia under Hacktoberfest'22.

**Comment by varunKT001** [comment]
@ravish036 Go ahead 🚀

**Comment by Anand271** [comment]
Hello Sir i have project to convert rgb to hex or hex to rgb using html css and javascript can i solve this issue

**Comment by varunKT001** [comment]
@Anand271 

Sorry, this issue is assigned to @ravish036

But you can contribute some other cool JavaScript project 😄
