### ISSUE TITLE
Title: Add Bookshelf App

### ISSUE THREAD

**Issue by Chidambaram-Sathappan** [varunKT001/awesome-javascript-projects#55]
### Describe your issue.

I would like to add my Animated Website Home Page to this repository

### Screenshots (if applicable).

![image](https://user-images.githubusercontent.com/83650869/194695849-0b1d69a9-ad6d-4504-b61c-495b94262faa.png)

**Comment by varunKT001** [comment]
@Chidambaram-Sathappan 

From the screenshot, it doesn't look like an animated website. Also, how did you use JavaScript in this project?

**Comment by Chidambaram-Sathappan** [comment]
@varunKT001 

It's just a HTML Project. Kindly Ignore.

Can this Bookshelf App be accepted?

**Bookshelf App storing data using Local Storage**

![image](https://user-images.githubusercontent.com/83650869/194699493-2bfee0a5-3b89-45d2-969b-908af4d3ae9c.png)

**Comment by Chidambaram-Sathappan** [comment]
PR : #56
