### ISSUE TITLE
Title: Pet conversation

### ISSUE THREAD

**Issue by LelePG** [varunKT001/awesome-javascript-projects#62]
### Describe your issue.

This project will be a chat where you can talk to a cat, or a dog. You'll be able to say something in the chat and will get an automatic response from a cat or a dog.

### Additional context (if any)

HTML and CSS will be used to build the interface, and Javascript will be responsible for giving you the answers when you talk to the pet.

**Comment by varunKT001** [comment]
@LelePG

That sounds quite fascinating. You can work on it 🚀
