### ISSUE TITLE
Feature Request: UI improvment & Responsive design for Github-Search-Profile-App

### ISSUE THREAD

**Issue by SubxX** [varunKT001/awesome-javascript-projects#69]
### Is your feature request related to a problem? Please describe.

Right now the design isn't very eye-catching and also it isn't mobile friendly.

### Describe the solution you'd like.

I would like to work on this project to improve the following things

- Overall design
- Responsiveness (Mobile friendly design)

**Comment by varunKT001** [comment]
@SubxX

Are you talking about the website of this repository?

**Comment by SubxX** [comment]
No the project named `Github-Search-Profile-App` in the projects directory

**Comment by varunKT001** [comment]
@SubxX That would be awesome, go ahead 🚀

**Comment by SubxX** [comment]
can you have a look at it @varunKT001
