### ISSUE TITLE
Feature Request: Update ReadMe

### ISSUE THREAD

**Issue by codeboyfriend** [varunKT001/awesome-javascript-projects#7]
### Is your feature request related to a problem? Please describe.

Add Technologies used to the ReadMe to give better understanding to the contributors

### Describe the solution you'd like.

Fork the repo and update the readme

**Comment by varunKT001** [comment]
@codeboyfriend The technologies used are evident from the repository title. Also, the README is dynamically generated on each push. Currently, there is no need to add any section for technology.

You can now contribute by adding some fantastic HTML, CSS, and JavaScript-based projects.
