### ISSUE TITLE
Feature Request: UI improvment & todo persistance for Todo app

### ISSUE THREAD

**Issue by SubxX** [varunKT001/awesome-javascript-projects#71]
### Is your feature request related to a problem? Please describe.

Right now there is no option to persist the todos it goes back to square one after refresh.

### Describe the solution you'd like.

I would like to work on this project to improve the following things

- Persist todo in local storage 
- Improve the design

**Comment by varunKT001** [comment]
@SubxX Go ahead 🚀

**Comment by SubxX** [comment]
PR created @varunKT001
