### ISSUE TITLE
Title: Height Converter Project

### ISSUE THREAD

**Issue by Drishti-jain21** [varunKT001/awesome-javascript-projects#74]
### Describe your issue.

I want to add a new project, which will convert height from Feet+Inches to Centimeter
It will be made using JavaScript, HTML and CSS
It will have calculate and reset buttons

**Comment by varunKT001** [comment]
@Drishti-jain21 Go ahead 🚀

**Comment by codeansh20** [comment]
SIr can u please assign this task to me i would love to contribute
