### ISSUE TITLE
Title: Loan Calculator

### ISSUE THREAD

**Issue by Drishti-jain21** [varunKT001/awesome-javascript-projects#75]
### Describe your issue.

I want to add a project where user can calculate the loan using the amount, rate and year
It will have calculate and reset button

**Comment by varunKT001** [comment]
@Drishti-jain21 Go ahead 🚀

**Comment by 035pratheeksha** [comment]
@varunKT001 
Heyy, I would like to add loan calculator code using javascript.
Please assign this to me.

**Comment by varunKT001** [comment]
@035pratheeksha Already assigned to @Drishti-jain21 

You can create your issues for the projects you want to build. 😄

**Comment by 035pratheeksha** [comment]
> @035pratheeksha Already assigned to @Drishti-jain21
> 
> You can create your issues for the projects you want to build. 😄

okay,Thankyou.
