### ISSUE TITLE
Title: TicTacToe

### ISSUE THREAD

**Issue by s0hamn** [varunKT001/awesome-javascript-projects#82]
### Describe your issue.

We all played this game with a pen and paper in childhood.
This is a simple web version of the game which you can play with your friends.

### Screenshots (if applicable).

![image](https://user-images.githubusercontent.com/70147659/195621877-e47d2ade-03b5-482e-a2d0-42afa34bb4f4.png)

**Comment by varunKT001** [comment]
@s0hamn Go ahead 🚀 

PS: Make sure that you don't use any libraries.
