### ISSUE TITLE
Feature Request: Default system preference light-dark-mode-toggle app

### ISSUE THREAD

**Issue by SubxX** [varunKT001/awesome-javascript-projects#83]
### Is your feature request related to a problem? Please describe.

Right now it does not apply dark/light mode based on the default system preference  we have to manually choose it and upon refresh it also goes back to the initial theme

### Describe the solution you'd like.

I would like to work on this project to improve the following things

- Apply mode based on system preference 
- Persist mode on local storage so that upon refresh we don't loose the state

**Comment by varunKT001** [comment]
@SubxX You can work on it 🚀 
BTW please mention which project you are talking about 😅

**Comment by SubxX** [comment]
I am talking about the `light-dark-mode-toggle` app inside projects directory

**Comment by SubxX** [comment]
PR created @varunKT001
